### ISSUE TITLE
Compile error in 9.1.0

### ISSUE THREAD

**Issue by leaumar** [krzkaczor/ts-essentials#281] opened 2021-12-24 14:38 UTC
Upgrading ts-essentials from 9.0.0 to 9.1.0 causes a compile error in my project (but not on any of my own sources):

```
➤ YN0000: executing [tsc]: tsc
../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts:282:28 - error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<
T[K]>'.
  Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
    Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
      Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
        Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
          Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
            Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
              Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
                Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
                  Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.

282           ? DeepOmit<T[K], Filter[K & keyof Filter]>
```

It's a yarn 3.1.0 project (pnp enabled) with ts 4.5.4. My intellij doesn't show any issue in this file. Not sure anything else could be relevant. Full [source](https://gitlab.com/Marnes/webextensions/-/tree/renovate/ts-essentials-9.x) and [build](https://gitlab.com/Marnes/webextensions/-/jobs/1918108687)

**Comment by Beraliv** [comment] 2021-12-24 15:41
Hey @leaumar 👋

Thank you for the report!

I'm on it, I will check it in a moment

**Comment by Beraliv** [comment] 2021-12-24 15:45
So I see this tree at the moment

```bash
➜ yarn why ts-essentials
├─ copy-selected-links@workspace:extensions/copy-selected-links
│  └─ ts-essentials@npm:9.1.0 [cf04e] (via npm:^9.1.0 [cf04e])
│
├─ doubleclick-image-downloader@workspace:extensions/doubleclick-image-downloader
│  └─ ts-essentials@npm:9.1.0 [cf04e] (via npm:^9.1.0 [cf04e])
│
├─ image-background-color-picker@workspace:extensions/image-background-color-picker
│  └─ ts-essentials@npm:9.1.0 [cf04e] (via npm:^9.1.0 [cf04e])
│
├─ plain-text-linker@workspace:extensions/plain-text-linker
│  └─ ts-essentials@npm:9.1.0 [cf04e] (via npm:^9.1.0 [cf04e])
│
└─ public-ip-display@workspace:extensions/public-ip-display
   └─ ts-essentials@npm:9.1.0 [cf04e] (via npm:^9.1.0 [cf04e])
```

**Comment by Beraliv** [comment] 2021-12-24 15:54
I added `node-gyp` to be able to install all dependencies and I could then reproduce the problem for `tsc`:

```
➜ yarn workspaces foreach run tsc
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(282,28): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(326,36): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K & keyof T]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(282,28): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(326,36): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K & keyof T]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(282,28): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(326,36): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K & keyof T]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(282,28): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(326,36): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K & keyof T]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ➤ YN0000: executing [tsc]: tsc
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(282,28): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: ../../.yarn/__virtual__/ts-essentials-virtual-35892e1d39/0/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip/node_modules/ts-essentials/dist/types.d.ts(326,36): error TS2344: Type 'Filter[K & keyof Filter]' does not satisfy the constraint 'DeepModify<T[K & keyof T]>'.
➤ YN0000:   Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:     Type 'Filter[string]' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:       Type 'unknown' is not assignable to type 'DeepModify<T[K & keyof T]>'.
➤ YN0000:         Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:           Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:             Type 'Filter[K & keyof Filter]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:               Type 'Filter[string] | Filter[number] | Filter[symbol]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                 Type 'Filter[string]' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000:                   Type 'unknown' is not assignable to type 'T[K & keyof T] extends WeakMap<infer K, infer E> ? WeakMap<K, DeepModify<E>> : never'.
➤ YN0000: Done in 12s 533ms
```

**Comment by Beraliv** [comment] 2021-12-24 16:09
So what I want to check is how it's used in your sub-dependencies (I don't know how to check it with PnP)

Can you please help find the place or the example of usage?

I want to reproduce it in the isolated environment

**Comment by Beraliv** [comment] 2021-12-24 16:14
Okay, I found the way what to do:

1. I found the file `.yarn/cache/ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip`
2. Unzipped it, it created `node_modules` folder
3. I copied the file `.yarn/cache/node_modules/ts-essentials/dist/types.d.ts` to Playground – https://tsplay.dev/WK7MgW

And now I see the problem

**Comment by Beraliv** [comment] 2021-12-24 16:32
I will check what was changed since `4.4.4` – https://tsplay.dev/wj4E6m, but I don't see the error there

What I found that `unknown` is handled a bit differently and that can be an issue

**Comment by Beraliv** [comment] 2021-12-24 20:02
To be able to avoid this problem in the future, I will add CI checks for all supported TypeScript versions - https://github.com/krzkaczor/ts-essentials/pull/283

**Comment by leaumar** [comment] 2021-12-24 20:05
Thanks for the hard work 👍

**Comment by Beraliv** [comment] 2021-12-24 20:06
Merged the fix, will add CI checka and release it in https://github.com/krzkaczor/ts-essentials/pull/284

**Comment by Beraliv** [comment] 2021-12-29 11:51
It seems I fixed all the problems with the build and will release it today in https://github.com/krzkaczor/ts-essentials/pull/289

Please let me know if you have issues in the next version

If not, I will resolve it after that

Thanks again for the help 🙏

**Comment by leaumar** [comment] 2021-12-29 12:02
Great, thanks for the fix

**Comment by Beraliv** [comment] 2021-12-29 15:09
Released it now 🚀

**Comment by leaumar** [comment] 2021-12-29 19:43
Yay, now it fails to build on both CI and my laptop :)

```
PS D:\Projects\webextensions> yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 223ms
➤ YN0000: ┌ Fetch step                                                                      
➤ YN0019: │ @typescript-eslint-scope-manager-npm-5.8.0-5cf3a1f020-15f365a491.zip appears to be unused - removing
➤ YN0019: │ @typescript-eslint-types-npm-5.8.0-f2e019762c-eda7a2c462.zip appears to be unused - removing
➤ YN0019: │ @typescript-eslint-typescript-estree-npm-5.8.0-a4e61ffa5d-67f51754d1.zip appears to be unused - removing
➤ YN0019: │ @typescript-eslint-visitor-keys-npm-5.8.0-15ce34e26b-03a349d4a5.zip appears to be unused - removing
➤ YN0019: │ ts-essentials-npm-9.1.0-2e85644a24-686f242bb1.zip appears to be unused - removing
➤ YN0000: └ Completed in 3s 25ms
➤ YN0000: ┌ Link step
➤ YN0005: │ parcel-bundler@npm:1.12.5 lists build scripts, but its build has been explicitly disabled through configuration.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ ts-essentials@npm:9.1.1 [cf04e] must be built because it never has been before or the last one failed
➤ YN0009: │ ts-essentials@npm:9.1.1 [cf04e] couldn't be built successfully (exit code 1, logs can be found here: C:\Users\leaumar\AppData\Local\Temp\xfs-1dcbf089\build.log)
➤ YN0000: └ Completed in 1s 369ms
➤ YN0000: Failed with errors in 4s 723ms
```

```
# This file contains the result of Yarn building a package (ts-essentials@virtual:cf04e91f3032ef47df7a54b657158d966d2b34f22b60c9c1e867867abca6e30d1ae313a7fdec2f1375674d1054aa179a09ae3b6122f3d40ed02f02ab17d89158#npm:9.1.1)
# Script name: postinstall

[94m➤[39m YN0000: executing [[38;2;215;135;95mpostinstall[39m]: [38;2;135;175;255myarn setTsVersion[39m
➤ YN0000: executing [setTsVersion]: node scripts/sync-ts-version.js
D:\Projects\webextensions\.pnp.cjs:26438
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: D:\Projects\webextensions\.yarn\unplugged\ts-essentials-virtual-0c4fb1de04\node_modules\ts-essentials\scripts\sync-ts-version.js
Not found: D:\Projects\webextensions\.yarn\unplugged\ts-essentials-virtual-0c4fb1de04\node_modules\ts-essentials\scripts\sync-ts-version.js
Not found: D:\Projects\webextensions\.yarn\unplugged\ts-essentials-virtual-0c4fb1de04\node_modules\ts-essentials\scripts\sync-ts-version.js.js
Not found: D:\Projects\webextensions\.yarn\unplugged\ts-essentials-virtual-0c4fb1de04\node_modules\ts-essentials\scripts\sync-ts-version.js.json
Not found: D:\Projects\webextensions\.yarn\unplugged\ts-essentials-virtual-0c4fb1de04\node_modules\ts-essentials\scripts\sync-ts-version.js.node

    at Function.external_module_.Module._resolveFilename (D:\Projects\webextensions\.pnp.cjs:26437:55)
    at Function.external_module_.Module._load (D:\Projects\webextensions\.pnp.cjs:26236:48)
    at Function.moduleExports.runMain (D:\Projects\webextensions\.pnp.cjs:26487:31)
    at node:internal/main/run_main_module:17:47
```

Did you add a helper file `sync-ts-version` but forget to declare it somewhere?

**Comment by leaumar** [comment] 2021-12-29 19:46
Looks like you do a postinstall that tries to run a script that looks for the ts version and writes it to a transient file into the dependency or project to make the found version a runtime constant? Sounds hacky tbqh 😬

**Comment by Beraliv** [comment] 2021-12-29 20:50
> Looks like you do a postinstall that tries to run a script that looks for the ts version and writes it to a transient file into the dependency or project to make the found version a runtime constant? Sounds hacky to me tbqh 😬 , but maybe I'm interpreting it wrong, is that how it's done usually? I wouldn't know tbf.
> 
> Yarn says it can't find the file, did you forget to declare it somewhere? I've seen an error like this in yargs I think, when the `exports` field in package.json was missing entries.

Yeah, I do postinstall script that can break things now

And as there are different versions that we currently support, now it's even more difficult to handle all these things

**Comment by Beraliv** [comment] 2021-12-29 20:52
Let's discuss it in https://github.com/krzkaczor/ts-essentials/issues/290

Probably file is missing and now it's also not working

Sorry for the inconvenience 😔

**Comment by Beraliv** [comment] 2021-12-30 11:17
@leaumar I will release it in https://github.com/krzkaczor/ts-essentials/pull/292

**Comment by Beraliv** [comment] 2021-12-30 11:19
Done ✅

**Closed** 2021-12-30 16:45 UTC
